apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: image-processing-cloud
  name: image-processing-cloud
spec:
  ports:
    - name: "5052"
      port: 5052
      targetPort: 5052
  selector:
    io.kompose.service: image-processing-cloud
status:
  loadBalancer: {}
