- hosts: master
  become: yes
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
    - master
  tasks:
    - name: Check Docker Version
      command: docker -v
      register: dockerVersion
    - name: Print Version
      debug:
        msg: "Docker Version: {{ dockerVersion.stdout }}"
    - name: Check Kubernetes Version
      command: kubectl version --short
      register: kubernetesVersion
    - name: Print Version
      debug:
        msg: "Kubernetes Version: {{ kubernetesVersion.stdout }}"

- hosts: node
  become: yes
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
    - node
  tasks:
    - name: Check Docker Version
      command: docker -v
      register: dockerVersion
    - name: Print Version
      debug:
        msg: "Docker Version: {{ dockerVersion.stdout }}"

- hosts: master, node
  become: yes
  tasks:
    - name: Fetch the file from the master to local
      run_once: yes
      fetch: src=/etc/kubeedge/certs.tgz dest=buffer/ flat=yes
      when: "{{inventory_hostname == 'server1'}}"
    - name: Copy the file from local to node
      copy: src=buffer/certs.tgz dest=/etc/kubeedge/
      when: "{{inventory_hostname == 'server2'}}"

- hosts: node
  become: yes
  roles:
    - kube-edge-worker
  tasks:
    - name: Check Docker Version
      command: docker -v
      register: dockerVersion
    - name: Print Version
      debug:
        msg: "Docker Version: {{ dockerVersion.stdout }}"
    - name: Check Kubernetes Version
      command: kubectl version --short
      register: kubernetesVersion
    - name: Print Version
      debug:
        msg: "Kubernetes Version: {{ kubernetesVersion.stdout }}"
