---
- name: Install Package Dependencies for
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - golang
    - make
    state: present
- name: check go version
  shell: go version
- name: download kubeedge
  ansible.builtin.unarchive:
    src: https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/keadm-v1.4.0-linux-amd64.tar.gz
    dest: /root
    remote_src: yes
- name: Move keadm bin
  command: mv /root/keadm-v1.4.0-linux-amd64/keadm/keadm /usr/local/bin
#- name: Copy Kube Config
#  command: cp /etc/kubernetes/admin.conf $HOME/.kube/config
- name: initialize kubeedge
  shell: keadm init --advertise-address="{{ hostvars['kubeedge-cluster-master-0']['ansible_host'] }}"
- name: Generate Token
  command: keadm gettoken --kube-config=/etc/kubernetes/admin.conf
  register: generate_token_output
- name: Set token
  set_fact:
    keadm_token: "{{ generate_token_output.stdout }}"
