version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  cloudworker:
    image: ecobench/sensor-cloud:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
  edgeworker1:
    image: ecobench/sensor-edge:latest
    restart: unless-stopped
    ports:
      - "9080:8080"
    environment:
    - targetNode.host=cloudworker
    - targetNode.url=/sensorData
    - edge.endpoints=http://edgeworker2:8080/alert
  edgeworker2:
    image: ecobench/sensor-edge:latest
    restart: unless-stopped
    ports:
      - "10080:8080"
    environment:
    - targetNode.host=cloudworker
    - targetNode.url=/sensorData
    - edge.endpoints=http://edgeworker1:8080/alert
  sensor:
    image: ecobench/sensor-edge-device:latest
    restart: unless-stopped
    environment:
    - DEVICE_TYPE=sensor
    - WORKER_IP=http://edgeworker1
    - WORKER_PORT=8080
    - WORKER_ENDPOINT=sensorData
  image-processing-cloud:
    image: ecobench/image-processing-cloud:latest
    restart: unless-stopped
    ports:
      - "5052:5052"
    environment:
    - IMAGE_CLOUD_PORT=5052
    - IMAGE_EDGE_IP=image-processing-edge
    - IMAGE_EDGE_PORT=5051
    - MONGODB_IP=mongodb
    - MONGODB_PORT=27017
  image-processing-edge:
    image: ecobench/image-processing-edge:latest
    restart: unless-stopped
    ports:
      - "5051:5051"
    environment:
    - IMAGE_EDGE_PORT=5051
    - IMAGE_CLOUD_IP=image-processing-cloud
    - IMAGE_CLOUD_PORT=5052
  camera-edge-device:
    image: ecobench/camera-edge-device:latest
    restart: unless-stopped
    environment:
    - IMAGE_EDGE_IP=image-processing-edge
    - IMAGE_EDGE_PORT=5051
