version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  cloudworker:
    image: docker.pkg.github.com/eco-bench/eco-bench/sensor-cloud:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
  edgeworker1:
    image: docker.pkg.github.com/eco-bench/eco-bench/sensor-edge:latest
    restart: unless-stopped
    ports:
      - "9080:8080"
    environment:
    - targetNode.host=cloudworker
    - targetNode.url=/sensorData
    - edge.endpoints=http://edgeworker2:8080/alert
  edgeworker2:
    image: docker.pkg.github.com/eco-bench/eco-bench/sensor-edge:latest
    restart: unless-stopped
    ports:
      - "10080:8080"
    environment:
    - targetNode.host=cloudworker
    - targetNode.url=/sensorData
    - edge.endpoints=http://edgeworker1:8080/alert
  sensor:
    image: docker.pkg.github.com/eco-bench/eco-bench/sensor-edge-device:latest
    restart: unless-stopped
    environment:
    - DEVICE_TYPE=sensor
    - WORKER_IP=http://edgeworker1
    - WORKER_PORT=8080
    - WORKER_ENDPOINT=sensorData
