---
- name: Change the working directory to /etc/kubeedge/ before executing the command
  shell: sudo tar -xvzf certs.tgz
  args:
    chdir: /etc/kubeedge/
- name: stop edgecore.service and remove service file
  shell: sudo systemctl stop edgecore.service && sudo rm /etc/systemd/system/edgecore.service && sudo systemctl daemon-reload
- name: go to bin directory and Setup Edge Side (KubeEdge Worker Node)
#todo template ip
  shell: ./keadm join --cloudcore-ipport=35.193.18.16:10000
  become: yes
  args:
    chdir: /src/github.com/kubeedge/kubeedge/_output/local/bin
