apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: image-processing-edge
  name: image-processing-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-processing-edge
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: image-processing-edge
    spec:
      containers:
        - env:
            - name: IMAGE_CLOUD_IP
              value: image-processing-cloud
            - name: IMAGE_CLOUD_PORT
              value: "5052"
            - name: IMAGE_EDGE_PORT
              value: "5051"
            -name: IMAGE_ACCEPTANCE_RATE
              value: "0.5"
          image: registry.hub.docker.com/ecobench/image-processing-edge
          name: image-processing-edge
          ports:
            - containerPort: 5051
          resources: {}
      imagePullSecrets:
        - name: github-regsecr
      restartPolicy: Always
status: {}
