- hosts: server
  become: true
  tasks:
  - name: Install mongo client
    shell: |
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
      echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org-shell
  - name: Create a directory if it does not exist
    file:
      path: /etc/scripts
      state: directory
      mode: '0755'
  - name: copy files from localhost to remote 
    copy:
      src: "{{ item }}"
      dest: /etc/scripts
      owner: root
      mode: 600
    loop:
      - collector.sh
  - name: check whats in the directory
    shell: ls /etc/scripts
    register: shell_output
  - name: print output
    debug: 
      msg: "This is a file {{ item }}"
    loop: "{{ shell_output.stdout_lines }}"
  - name: execute shell script
    async: 60 # Maximum allowed time in Seconds
    poll: 5 # poll will check if the task is completed or not for every x secs
    ignore_errors: True
    shell: 
      cmd: bash collector.sh 30
      chdir: /etc/scripts
  - name: execute shell script
    register: cat_output
    ignore_errors: True
    shell: 
      cmd: cat stats.log
      chdir: /etc/scripts
  - name: print out
    debug: 
      msg: "{{ cat_output.stdout_lines }}"
# mongo -u testUser -p passw0rd 35.222.15.91/metrics

