- hosts: microk8s-master
  tasks:
    - name: Start Time
      command: date
      register: time
    - name: Print Start Time
      debug:
        msg: "time: {{ time.stdout }}"
        
- hosts: microk8s-master
  roles:
    - microk8s
  tasks:
    - name: Run join Node Command
      become: true
      command: microk8s add-node
      register: join_command1
    - name: Set token
      set_fact:
        join_token_1: "{{ join_command1.stdout_lines[4] }}"
    - name: Print join_token_1
      debug:
        msg: "time: {{ join_token_1 }}"
    - name: Run join Node Command
      become: true
      command: microk8s add-node
      register: join_command2
    - name: Set token
      set_fact:
        join_token_2: "{{ join_command2.stdout_lines[4] }}"
    - name: Print join_token_2
      debug:
        msg: "time: {{ join_token_2 }}"

- hosts: microk8s-worker-0
  roles:
    - microk8s
  vars: 
    tmp_variable: "lalala"
  tasks:
    - name: Print Join Command
      debug:
        msg: "{{ hostvars['microk8s-master']['join_token_1'] }}"
    - name: join cluster
      become: yes
      command: "{{ hostvars['microk8s-master']['join_token_1'] }}"
      ignore_errors: yes
      delay: 300

- hosts: microk8s-worker-1
  roles:
    - microk8s
  tasks:
    - name: Print Join Command
      debug:
        msg: "{{ hostvars['microk8s-master']['join_token_2'] }}"
    - name: join cluster
      become: yes
      command: "{{ hostvars['microk8s-master']['join_token_2'] }}"
      ignore_errors: yes
      delay: 300

- hosts: microk8s-master
  tasks:
    - name: Check Cluster Status
      become: yes
      command: microk8s kubectl get nodes
      register: cluster_status
    - name: Loop over lines in a file
      become: yes
      debug:
        var: item
      with_items: "{{ cluster_status.stdout_lines }}"
    - name: End Time
      command: date
      register: time
    - name: Print End Time
      debug:
        msg: "time: {{ time.stdout }}"