apiVersion: v1
kind: Service
metadata:
  name: sensor-ew2-service
spec:
  selector:
    app: sensor-ew2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-ew2-deployment
  labels:
    app: sensor-ew2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-ew2
  template:
    metadata:
      labels:
        app: sensor-ew2
    spec:
      containers:
        - name: sensor-ew2
          image: ecobench/sensor-edge:latest
          ports:
            - containerPort: 80
          envFrom:
          # The ConfigMap we want to use
          - configMapRef:
              name: sensor-ew2-config
      imagePullSecrets:
        - name: github-regsecr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-ew2-config
data:
  targetNode.host: "sensor-cw-service"
  targetNode.url: "/sensorData"
  edge.endpoints: "http://sensor-ew1-service:80/alert"
