apiVersion: v1
kind: Service
metadata:
  name: sensor-ew1-service
spec:
  selector:
    app: sensor-ew1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-ew1-deployment
  labels:
    app: sensor-ew1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-ew1
  template:
    metadata:
      labels:
        app: sensor-ew1
    spec:
      containers:
        - name: sensor-ew1
          image: docker.pkg.github.com/eco-bench/eco-bench/sensor-edge:latest
          ports:
            - containerPort: 80
          envFrom:
          # The ConfigMap we want to use
          - configMapRef:
              name: sensor-ew1-config
      imagePullSecrets:
        - name: github-regsecr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-ew1-config
data:
  targetNode.host: "sensor-cw-service"
  targetNode.url: "/sensorData"
  targetNode.port: "8080"
  edge.endpoints: "http://sensor-ew2-service:80/alert"
