name: Build Image Processing Cloud Docker Image

on:
  workflow_dispatch:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths:
      - dummy/image-processing-cloud/**
  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: image-processing-cloud
  
defaults:
  run:
    working-directory: dummy/image-processing-cloud

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publisch to Github Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/$IMAGE_NAME
          tags: lastest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ github.repository }}/$IMAGE_NAME
          tags: lastest, ${{ github.run_number }}
