name: Build Image Processing Edge Docker Image

on:
  workflow_dispatch:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths:
      - dummy/image-processing-edge/**
  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image-processing-edge
  REPOSITORY: ecobench
  
defaults:
  run:
    working-directory: dummy/image-processing-edge

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Build image
        run: docker build . --tag ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ecobench
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Run docker push
        run: docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}

      - name: Name of Image 
        run: echo "${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}"
