name: Build Image Processing Cloud Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - dummy/image-processing-cloud/**

env:
  IMAGE_NAME: image-processing-cloud
  REPOSITORY: ecobench
  
defaults:
  run:
    working-directory: dummy/image-processing-cloud

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build image
        run: docker build . --tag ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ecobench
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Run docker push
        run: docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}

      - name: Name of Image 
        run: echo "${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}"
