name: "Destroy Environment"

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Destroy"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Move Public Key for current User
      - name: Create Public Key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa.pub
          echo '${{ secrets.PUBLIC_KEY }}' >> ~/.ssh/id_rsa.pub

      - name: Download cluster state artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: terraform.yml
          name: my-artifact
          path: .

      - name: terraform init
        run: terraform init

      - name: destroy cluster state
        run: terraform destroy -var-file tfvars.json -auto-approve
