---
- name: Install Package Dependencies for
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - golang
    - make
    state: present
- name: check go version
  shell: go version
- name: download kubeedge
  git:
    repo: 'https://github.com/kubeedge/kubeedge.git'
    dest: $GOPATH/src/github.com/kubeedge/kubeedge
    clone: yes
    update: no
  become: yes
- name: download kubeedge
  ansible.builtin.unarchive:
    src: https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/keadm-v1.4.0-linux-amd64.tar.gz
    dest: /root
    remote_src: yes
- name: Move keadm bin
  command: mv /root/keadm-v1.4.0-linux-amd64/keadm/keadm /usr/local/bin
- name: Join EdgeNode
  command: keadm join --cloudcore-ipport={{hostvars['kubeedge-cluster-master-0']['ansible_host']}}:10000 --token={{keadm_token}}
- name: Create a etc/kubeedge if it does not exist
  ansible.builtin.file:
    path: etc/kubeedge
    state: directory
    mode: '0755'
