---
- name: Install Package Dependencies for
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - golang
    - make
    state: present
- name: check go version
  shell: go version
- name: download kubeedge
  git:
    repo: 'https://github.com/kubeedge/kubeedge.git'
    dest: $GOPATH/src/github.com/kubeedge/kubeedge
    clone: yes
    update: no
  become: yes
- name: Run 'keadm' target as root
  community.general.make:
    chdir: /src/github.com/kubeedge/kubeedge
    target: keadm
  become: yes
- name: Create a etc/kubeedge if it does not exist
  ansible.builtin.file:
    path: etc/kubeedge
    state: directory
    mode: '0755'
